server:
  port: 90
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 2000
      time-between-eviction-runs-millis: 6000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      pool-prepared-statements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
  redis:
      database: 4
      host: localhost
      port: 6379
      timeout: 15000
      jedis:
        pool:
          max-active: 3000
          max-idle: 8
          min-idle: 0
          max-wait: -1
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /vinspier
    username: vinspier
    password: vinspier
    # 缺省的交换机名称 发送消息如果不指定交换机就会使用这个
    template:
        exchange: sec_kill
    # 消息生产者 发送发回
    publisher-returns: true
    # 消息生产者 发送确认
    publisher-confirm-type: correlated
    # 消费者ack确认机制开启 采用手动模式 默认为auto
    listener:
      simple:
        # 消费者 手动ack确认
        acknowledge-mode: manual
        # 消费者每次从队列获取的消息数量。此属性当不设置时为：轮询分发，设置为1为：公平分发
        prefetch: 1

mybatis:
  type-aliases-package: com.vinspier.seckill.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 是否可以使用列的别名
    use-column-label: true

# log
logging:
  level:
    com:
      spring: info
      vinspier:
        seckill:
          dao: debug
  file:
    path: /seckill_Log

# 自定义参数

customize:
  # 暴露秒杀商品ID加密的 盐
  exposedSalt: sdfgh%$%hr123thgj@#@@!WSDFD123
  # 抢到秒杀商品 等待支付时间 单位ms
  payedWaited: 900000
  # 每秒限流数
  rateLimited: 5
  # 获取限流机会等待时间 单位ms
  rateLimiterWait: 500



